FOUNDATIONS: Add VideoMetadata Test
SamandarDeveloper19/WatchWave pull request #16
Opened 2024-05-17 15:11 UTC by UmidjonDeveloperr

2024-05-17 15:26 UTC, ZafarUrakov commented
approved

2024-05-20 16:53 UTC, ElbekDeveloper requested changes

2024-05-20 16:53 UTC, ElbekDeveloper commented on WatchWave.Api.Tests.Unit/Services/Foundations/VideoMetadatas/VideoMetadataServiceTests.Logic.Add.cs
> +﻿using FluentAssertions;
Header

2024-05-20 16:53 UTC, ElbekDeveloper commented on WatchWave.Api.Tests.Unit/Services/Foundations/VideoMetadatas/VideoMetadataServiceTests.Validation.Add.cs
> +			VideoMetadata nullVideoMetadata = null;
<Nullable>disalbe</Nullable>

2024-05-20 16:53 UTC, ElbekDeveloper commented on WatchWave.Api/Brokers/Storages/IStorageBroker.VideoMetadatas.cs
> +    public partial interface IStorageBroker
internal partial

2024-05-20 16:53 UTC, ElbekDeveloper commented on WatchWave.Api/Models/VideoMetadatas/Exceptions/VideoMetadataValidationException.cs
> +        { }
Bu eski usul. Yangisida qiymat bo'lmaydi

2024-05-24 17:18 UTC, ElbekDeveloper commented on WatchWave.Api/Brokers/Storages/StorageBroker.VideoMetadatas.cs
> +    public partial class StorageBroker
Internal

2024-05-24 17:18 UTC, ElbekDeveloper commented on WatchWave.Api/Brokers/Storages/StorageBroker.cs
> +    public partial class StorageBroker : EFxceptionsContext, IStorageBroker
Internal

2024-05-24 17:20 UTC, ElbekDeveloper commented on WatchWave.Api/Brokers/Storages/StorageBroker.cs
> +    public partial class StorageBroker : EFxceptionsContext, IStorageBroker
[Buni ko'ring](https://www.youtube.com/watch?v=dweVExK8IPs)

2024-05-24 17:20 UTC, ElbekDeveloper commented on WatchWave.Api/Models/VideoMetadatas/Exceptions/AlreadyExistVideoMetadataException.cs
> +        public AlreadyExistVideoMetadataException(string message, Exception innerException)
AlreadyExistsVideoMetadataException

2024-05-24 17:20 UTC, ElbekDeveloper commented on WatchWave.Api/Services/VideoMetadatas/VideoMetadataService.Exceptions.cs
> +	public partial class VideoMetadataService
Internal

2024-05-24 17:21 UTC, ElbekDeveloper commented on WatchWave.Api/Services/VideoMetadatas/VideoMetadataService.Validations.cs
> +
CreatedDate != Updated

2024-05-24 17:21 UTC, ElbekDeveloper commented on WatchWave.Api/Services/VideoMetadatas/VideoMetadataService.Validations.cs
> +
CreatedDate is not recent

2024-05-24 17:21 UTC, ElbekDeveloper commented on WatchWave.Api/Services/VideoMetadatas/VideoMetadataService.cs
> +
Bu ortiqcha qatorlar

2024-05-24 17:21 UTC, ElbekDeveloper commented on WatchWave.Api/Services/VideoMetadatas/VideoMetadataService.cs
> +				return await this.storageBroker.InsertVideoMetadataAsync(videoMetadata);
Bir tab orqaga

2024-05-24 17:22 UTC, ElbekDeveloper commented on WatchWave.Api.Tests.Unit/Services/Foundations/VideoMetadatas/VideoMetadataServiceTests.Exception.Add.cs
> +				= new("Video Metadata dependency error occured. Fix errors and try again.",
Bu standard emas

2024-05-24 17:22 UTC, ElbekDeveloper commented on WatchWave.Api.Tests.Unit/Services/Foundations/VideoMetadatas/VideoMetadataServiceTests.Exception.Add.cs
> +					Times.Once());
Qavs kerakmas

2024-05-24 17:22 UTC, ElbekDeveloper commented on WatchWave.Api.Tests.Unit/Services/Foundations/VideoMetadatas/VideoMetadataServiceTests.Validation.Add.cs
> +				values: "Date is required.");
Buni formatini to'g'rilang

2024-05-24 17:25 UTC, ElbekDeveloper commented
`DbUpdateException` ham handle qilinsin

2024-05-28 18:21 UTC, merged